### PR TITLE
pass dropout param to ScaledDotProductAttention

### PR DESCRIPTION
**Pull request by zalivnaja**

### CODE REVIEW

**Comment by ivan-bilan** [comment]
Was this intentional by any chance?

**Comment by zalivnaja** [comment]
Yep, it is for reproducibility of results when using fixed seed

**Comment by ivan-bilan** [comment]
how so? Should the ScaledDotProductAttention have a dropout set to 0.1 for the results of the paper to be reproduced? Or did they use dropout=0.1 throughout the whole model?

**Comment by huangnengCSU** [comment]
It seems that if each ScaledDotProductAttention uses a dropout, the result will be better. But it is just in my experiment.

**Pull request closed without merging**
