### PR TITLE
fix bugs for expanding mu and sigma

### PR DESCRIPTION
**Pull request by eriche2016**

### CODE REVIEW

**Comment by jadore801120** [comment]
Hi @eriche2016 ,

Thanks for this pull request!

I mistakenly thought that the `torch.std` and `torch.mean` will keep the original dimension before, but I check the document and found out that they will not.
It is very weird that I haven't run into any runtime error with `PyTorch (0.1.12_2)`.
Anyway, I think it is good to make the intent clear! so thanks for pointing out!

However, I think that your modification exists an Syntax error. Please take a look.
On the other hand, I think set up the `keepdim` parameter in these two operations will make the intent clearer.

Thank you!

**Comment by eriche2016** [comment]
yes, a redundant dot was mistakenly used. keepdim is a good solution.  Any way, i will close this pr.

**Comment by eriche2016** [comment]
hi, i am not sure why you donot have this runtime error, By the way, i have achieved far better results on the default multi30k dataset, below is a snapshot:
```
 - (Training)   ppl:  1.00401, accuracy: 99.900 %, elapse: 3.343 min
0 / 14
  - (Validation) ppl:  1.00827, accuracy: 99.831 %, elapse: 0.034 min
Epoch 82 / 100

```

**Comment by jadore801120** [comment]
Hi @eriche2016 ,

Thanks for the pointing out!
The bug is just fixed in [9bb054a](https://github.com/jadore801120/attention-is-all-you-need-pytorch/commit/9bb054ac93a5b73b5c3517df86ae9f5292bbf986).
Please take a look!
Thank you!

Yu-Hsiang

**Pull request closed without merging**
